Repository growingio/gio-design, pull requests merged in 2020-09, with the labels that each got.

#173 fix(token): update some tokens related with font
  packages/components/src/components/alert/style/index.less
  packages/components/src/components/banner/style/index.less
  packages/components/src/components/tag/style/index.less
  packages/components/src/components/toggles/style/index.less
  packages/tokens/properties/font.json
  packages/tokens/properties/size/font.json
Labels: add to next version, 🔑 token

#174 fix(website，tokens，icons，components): 修改button的一些问题
  packages/components/src/components/button/LoadingIcon.tsx
  packages/components/src/components/button/button.tsx
  packages/components/src/components/button/style/index.less
  packages/components/src/components/button/style/mixin.less
  packages/components/src/components/tree/style/index.less
  packages/components/src/components/upload/style/index.less
  packages/components/src/components/upload/triggers/InputTrigger.tsx
  packages/icons/src/LoadingOutlined.tsx
  packages/icons/src/index.tsx
  packages/icons/svgs/loading-outlined.svg
  packages/icons/svgs/loading-white-outlined.svg
  packages/tokens/properties/radius.json
  packages/tokens/properties/size/font/button.json
  packages/tokens/properties/weight.json
  packages/website/src/components/basic/loading/demos/index.less
  packages/website/src/components/basic/loading/demos/indicator.tsx
  packages/website/src/resources/iconDemos/basic.tsx
Labels: add to next version, 📎 icon, 🔑 token

#181 fix(checkbox): update checkbox props and text margin
  packages/components/src/components/checkbox/__tests__/__snapshots__/checkbox.test.js.snap
  packages/components/src/components/checkbox/__tests__/__snapshots__/group.test.js.snap
  packages/components/src/components/checkbox/checkbox.tsx
  packages/components/src/components/checkbox/group.tsx
  packages/components/src/components/checkbox/interface.tsx
  packages/components/src/components/checkbox/style/index.less
  packages/components/src/components/input/BaseInput.tsx
  packages/components/src/components/radio/style/index.less
  packages/components/src/components/toast/__tests__/index.test.js
  packages/icons/src/CheckOutlined.tsx
  packages/icons/src/index.tsx
  packages/icons/svgs/check-outlined.svg
  packages/tokens/properties/color/background.json
  packages/tokens/properties/color/border.json
  packages/tokens/properties/shadow.json
  packages/website/src/components/functional/tree/demos/icon.tsx
Labels: add to next version, 📎 icon, 🔑 token

#176 fix(components): fix bug in Modal
  packages/components/src/components/modal/Modal.tsx
  packages/components/src/components/modal/StepModal.tsx
  packages/website/src/components/functional/modal/demo/maskClose.tsx
  packages/website/src/components/functional/modal/index.zh-CN.md
Labels: add to next version

#200 style(checkbox): align check icon when be used to Table
  packages/components/src/components/checkbox/style/index.less
  packages/website/src/components/functional/dropdown/demo/base.tsx
  packages/website/src/components/functional/dropdown/demo/other.tsx
Labels: add to next version, 🐛 bug

#204 docs: @gio-design/components 20.9.1 change log
  packages/components/package-lock.json
  packages/components/package.json
  packages/icons/package.json
  packages/website/src/develop/changelog.en-US.md
  packages/website/src/develop/changelog/components.en-US.md
  packages/website/src/develop/changelog/components.zh-CN.md
  packages/website/src/develop/changelog/icons.en-US.md
  packages/website/src/develop/changelog/icons.zh-CN.md
Labels: 📃 documentation

#232 fix(checkbox): 上次修改checkbox样式改的地方不对,fix
  packages/components/src/components/checkbox/style/index.less
  packages/components/src/components/tag/interface.ts
Labels: add to next version

#266 docs: @gio-design/components 20.9.6 change log
  packages/components/package.json
  packages/icons/package.json
  packages/tokens/package.json
  packages/website/src/develop/changelog/components.en-US.md
  packages/website/src/develop/changelog/components.zh-CN.md
  packages/website/src/develop/changelog/icons.en-US.md
  packages/website/src/develop/changelog/icons.zh-CN.md
  packages/website/src/develop/changelog/tokens.zh-CN.md
Labels: 📃 documentation

#268 Update palette.json
  packages/tokens/properties/palette.json
Labels: add to next version, 🔑 token

#279 fix(loading): loading mask style error
  packages/components/src/components/loading/style/index.less
Labels: add to next version, 🐛 bug

#277 Update spacing.json
  packages/tokens/properties/size/spacing.json
Labels: add to next version, 🔑 token

#276 style(DatePicker): refactor icon & zIndex
  packages/components/src/components/date-picker/__tests__/__snapshots__/data-picker.spec.js.snap
  packages/components/src/components/date-picker/datePicker.tsx
  packages/components/src/components/date-picker/dateRangePicker.tsx
  packages/components/src/components/date-picker/style/decadePanel.less
  packages/components/src/components/date-picker/style/index.less
  packages/components/src/components/date-picker/style/monthPanel.less
  packages/components/src/components/date-picker/style/yearPanel.less
Labels: add to next version, 🐛 bug

#280 docs: @gio-design/components 20.9.7 change log
  packages/components/package.json
  packages/icons/package.json
  packages/tokens/package.json
  packages/website/src/develop/changelog/components.en-US.md
  packages/website/src/develop/changelog/components.zh-CN.md
  packages/website/src/develop/changelog/icons.en-US.md
  packages/website/src/develop/changelog/icons.zh-CN.md
  packages/website/src/develop/changelog/tokens.zh-CN.md
  yarn.lock
Labels: 📃 documentation
