Repository growingio/gio-design, pull requests merged in 2020-10, with the labels that each got.

#290 feat(searchbar): add placeholder prop
  packages/components/src/components/searchBar/index.tsx
  packages/components/src/components/searchBar/interfaces.ts
Labels: add to next version, enhancement

#296 feat(date-picker): add rengePicker feature
  packages/components/src/components/date-picker/dateRangePicker.tsx
  packages/components/src/components/date-picker/interface.tsx
  packages/components/src/components/date-picker/style/index.less
  packages/website/src/components/functional/date-picker/demo/range.tsx
  packages/website/src/components/functional/date-picker/index.zh-CN.md
Labels: add to next version, enhancement

#317 fix: allow use value control selections;
  packages/components/src/components/select/Select.tsx
  packages/components/src/components/select/interface.ts
  packages/components/src/components/select/style/index.less
  packages/website/src/components/functional/select/demos/options.ts
  packages/website/src/components/functional/select/demos/search.tsx
  packages/website/src/components/functional/select/index.zh-CN.md
Labels: add to next version, 🐛 bug

#318 style(form): 根据stylelint的提示，修改了form组件中index.less中部分属性的顺序
  packages/components/src/components/form/style/index.less
Labels: add to next version, refactor

#367 feat(tooltip): add disabled prop
  packages/components/src/components/tooltip/Tooltip.tsx
  packages/components/src/components/tooltip/__tests__/Tooltip.test.js
  packages/components/src/components/tooltip/interface.ts
  packages/website/src/components/basic/tooltip/index.zh-CN.md
Labels: add to next version, enhancement
