Repository growingio/gio-design, pull requests merged in 2020-08, with the labels that each got.

#50 chore: components and tokens 20.8.0 changelog
  packages/components/package.json
  packages/playground/package.json
  packages/themes/package.json
  packages/tokens/package.json
  packages/website/package.json
  packages/website/src/develop/changelog/components.zh-CN.md
  packages/website/src/develop/changelog/tokens.zh-CN.md
Labels: documentation

#39 feat(loading): add loading component
  packages/components/src/components/loading/Loading.tsx
  packages/components/src/components/loading/__test__/Loading.test.js
  packages/components/src/components/loading/__test__/__snapshots__/Loading.test.js.snap
  packages/components/src/components/loading/index.tsx
  packages/components/src/components/loading/interface.ts
  packages/components/src/components/loading/style/index.less
  packages/components/src/index.ts
  packages/components/src/utils/hooks/debounceLoading.ts
  packages/icons/src/LoadingOutlinedBlack.tsx
  packages/icons/src/LoadingOutlinedWhite.tsx
  packages/icons/src/index.tsx
  packages/icons/svgs/loadingOutlinedBlack.svg
  packages/icons/svgs/loadingOutlinedWhite.svg
  packages/tokens/properties/color/background.json
  packages/tokens/properties/color/text.json
  packages/website/src/components/basic/loading/demos/base.tsx
  packages/website/src/components/basic/loading/demos/debounce.tsx
  packages/website/src/components/basic/loading/demos/index.less
  packages/website/src/components/basic/loading/demos/indicator.tsx
  packages/website/src/components/basic/loading/demos/size.tsx
  packages/website/src/components/basic/loading/demos/wrapper.tsx
  packages/website/src/components/basic/loading/index.zh-CN.md
Labels: add to next version

#46 feat(skeleton): add skeleton component
  packages/components/src/components/skeleton/Image.tsx
  packages/components/src/components/skeleton/Skeleton.tsx
  packages/components/src/components/skeleton/__test__/Skeleton.test.js
  packages/components/src/components/skeleton/__test__/__snapshots__/Skeleton.test.js.snap
  packages/components/src/components/skeleton/index.ts
  packages/components/src/components/skeleton/interface.ts
  packages/components/src/components/skeleton/style/index.less
  packages/components/src/index.ts
  packages/tokens/config.js
  packages/tokens/properties/color/background.json
  packages/website/src/components/basic/skeleton/demos/base.tsx
  packages/website/src/components/basic/skeleton/demos/contain.tsx
  packages/website/src/components/basic/skeleton/demos/image.tsx
  packages/website/src/components/basic/skeleton/index.zh-CN.md
Labels: add to next version

#49 feat(popconfirm): add popconfirm component
  .gitignore
  packages/components/src/components/button/button.tsx
  packages/components/src/components/popconfirm/Popconfirm.tsx
  packages/components/src/components/popconfirm/__tests__/Popconfirm.test.js
  packages/components/src/components/popconfirm/__tests__/__snapshots__/Popconfirm.test.js.snap
  packages/components/src/components/popconfirm/index.tsx
  packages/components/src/components/popconfirm/interface.ts
  packages/components/src/components/popconfirm/style/index.less
  packages/components/src/components/popover/style/index.less
  packages/components/src/index.ts
  packages/icons/src/Warning.tsx
  packages/icons/src/index.tsx
  packages/icons/svgs/warning.svg
  packages/tokens/properties/color/background.json
  packages/tokens/properties/color/text.json
  packages/tokens/properties/shadow.json
  packages/website/src/components/functional/popconfirm/demo/base.tsx
  packages/website/src/components/functional/popconfirm/demo/index.less
  packages/website/src/components/functional/popconfirm/demo/placement.tsx
  packages/website/src/components/functional/popconfirm/demo/visible.tsx
  packages/website/src/components/functional/popconfirm/index.zh-CN.md
Labels: add to next version, enhancement

#51 add tree component
  packages/components/src/components/config-provider/index.tsx
  packages/components/src/components/tree/Tree.tsx
  packages/components/src/components/tree/iconUtil.tsx
  packages/components/src/components/tree/index.tsx
  packages/components/src/components/tree/style/index.less
  packages/components/src/components/tree/style/index.ts
  packages/icons/src/CaretDownOutlined.tsx
  packages/icons/src/LoadingOutlinedBlack.tsx
  packages/icons/src/LoadingOutlinedWhite.tsx
  packages/icons/src/More.tsx
  packages/icons/src/Warning.tsx
  packages/icons/src/index.tsx
  packages/icons/svgs/caret-down-outlined.svg
  packages/tokens/properties/color/background.json
  packages/tokens/properties/color/text.json
  packages/tokens/properties/palette.json
  packages/tokens/properties/radius.json
  packages/website/src/components/functional/tree/demos/icon.tsx
  packages/website/src/components/functional/tree/demos/index.less
  packages/website/src/components/functional/tree/demos/index.tsx
  packages/website/src/components/functional/tree/index.zh-CN.md
Labels: add to next version

#34 添加toggles组件
  packages/components/src/components/toggles/__test__/toggles.test.js
  packages/components/src/components/toggles/index.tsx
  packages/components/src/components/toggles/style/index.less
  packages/components/src/components/toggles/toggles.tsx
  packages/tokens/properties/color/background.json
  packages/tokens/properties/color/border.json
  packages/tokens/properties/shadow.json
  packages/website/src/components/basic/toggles/demo/toggles.tsx
  packages/website/src/components/basic/toggles/demo/togglesActiveValue.tsx
  packages/website/src/components/basic/toggles/demo/togglesBackgroundColor.tsx
  packages/website/src/components/basic/toggles/demo/togglesDisabled.tsx
  packages/website/src/components/basic/toggles/demo/togglesSuffix.tsx
  packages/website/src/components/basic/toggles/index.zh-CN.md
Labels: add to next version, enhancement

#58 fix(avatar): update text "n+" with "+n" in the AvatarGroup last item
  packages/components/src/components/avatar/AvatarGroup.tsx
  packages/components/src/components/avatar/__tests__/AvatarGroup.test.js
  packages/components/src/components/avatar/__tests__/__snapshots__/AvatarGroup.test.js.snap
Labels: add to next version, bug

#52 feat(components): add sign component
  packages/components/src/components/sign/Dot.tsx
  packages/components/src/components/sign/Number.tsx
  packages/components/src/components/sign/__tests__/__snapshots__/sign.test.js.snap
  packages/components/src/components/sign/__tests__/sign.test.js
  packages/components/src/components/sign/index.tsx
  packages/components/src/components/sign/interface.ts
  packages/components/src/components/sign/style/index.less
  packages/components/src/components/sign/style/index.ts
  packages/components/src/components/sign/style/mixin.less
  packages/tokens/properties/color/background.json
  packages/website/src/components/basic/sign/demos/demo.less
  packages/website/src/components/basic/sign/demos/dot.tsx
  packages/website/src/components/basic/sign/demos/dotSize.tsx
  packages/website/src/components/basic/sign/demos/placement.tsx
  packages/website/src/components/basic/sign/demos/showZero.tsx
  packages/website/src/components/basic/sign/demos/sign.tsx
  packages/website/src/components/basic/sign/index.zh-CN.md
Labels: add to next version, enhancement

#53 Alert
  packages/components/src/components/alert/alert.tsx
  packages/components/src/components/alert/index.tsx
  packages/components/src/components/alert/style/index.less
  packages/components/src/stylesheet/theme.less
  packages/icons/src/CheckCircleFilled.tsx
  packages/icons/src/Close.tsx
  packages/icons/src/CloseCircleFilled.tsx
  packages/icons/src/InformationFilled.tsx
  packages/icons/src/Warning.tsx
  packages/icons/src/index.tsx
  packages/icons/svgs/check-circle-filled.svg
  packages/icons/svgs/close-circle-filled.svg
  packages/icons/svgs/close.svg
  packages/icons/svgs/information-filled.svg
  packages/icons/svgs/warning.svg
  packages/tokens/properties/color/background.json
  packages/tokens/properties/color/text.json
  packages/tokens/properties/palette.json
  packages/website/src/components/basic/alert/demo/alert.tsx
  packages/website/src/components/basic/alert/demo/alertClose.tsx
  packages/website/src/components/basic/alert/demo/alertDecription.tsx
  packages/website/src/components/basic/alert/demo/alertDefineClose.tsx
  packages/website/src/components/basic/alert/demo/alertIcon.tsx
  packages/website/src/components/basic/alert/demo/alertOnlyDecription.tsx
  packages/website/src/components/basic/alert/demo/alertStyle.tsx
  packages/website/src/components/basic/alert/index.zh-CN.md
Labels: add to next version, enhancement

#66 chore: set up ci with azure pipelines
  azure-pipelines.yml
Labels: enhancement

#65 docs(website): components & tokens 20.8.1 and icons 20.8.0 changelog
  packages/components/package.json
  packages/icons/package.json
  packages/playground/package.json
  packages/themes/package.json
  packages/tokens/package.json
  packages/website/.umirc.ts
  packages/website/package.json
  packages/website/src/develop/changelog.zh-CN.md
  packages/website/src/develop/changelog/components.zh-CN.md
  packages/website/src/develop/changelog/icons.zh-CN.md
  packages/website/src/develop/changelog/tokens.zh-CN.md
  yarn.lock
Labels: documentation

#63 fix(website): change class name that affect global
  packages/website/src/components/basic/tag/demos/basic.tsx
  packages/website/src/components/basic/tag/demos/closable.tsx
  packages/website/src/components/basic/tag/demos/hoverClose.tsx
  packages/website/src/components/basic/tag/demos/index.less
  packages/website/src/components/basic/tag/demos/prorupt.tsx
  packages/website/src/components/basic/tag/demos/version.tsx
Labels: bug

#69 refactor(components): update palette and othe tokens
  packages/components/src/components/link/style/index.less
  packages/components/src/components/radio/style/index.less
  packages/components/src/components/sign/style/index.less
  packages/components/src/stylesheet/index.less
  packages/tokens/properties/color/background.json
  packages/tokens/properties/color/border.json
  packages/tokens/properties/color/text.json
  packages/tokens/properties/palette.json
  yarn.lock
Labels: add to next version, token

#77 docs(website): components & tokens 20.8.2 and icons 20.8.1 changelog
  packages/components/package.json
  packages/icons/package.json
  packages/themes/package.json
  packages/tokens/package.json
  packages/website/package.json
  packages/website/src/develop/changelog.zh-CN.md
  packages/website/src/develop/changelog/components.zh-CN.md
  packages/website/src/develop/changelog/icons.zh-CN.md
  packages/website/src/develop/changelog/tokens.zh-CN.md
Labels: documentation

#78 docs(loading): show subtitle "参数说明" in loading doc
  packages/components/src/components/button/style/index.less
  packages/components/src/components/button/style/mixin.less
  packages/website/src/components/basic/loading/index.zh-CN.md
Labels: add to next version, bug

#62 feat(components): progress
  packages/components/src/components/progress/Progress.tsx
  packages/components/src/components/progress/__tests__/Progress.test.js
  packages/components/src/components/progress/__tests__/__snapshots__/Progress.test.js.snap
  packages/components/src/components/progress/index.tsx
  packages/components/src/components/progress/interface.ts
  packages/components/src/components/progress/style/index.less
  packages/components/src/index.ts
  packages/website/src/components/basic/progress/demos/index.tsx
  packages/website/src/components/basic/progress/index.zh-CN.md
Labels: add to next version, enhancement

#57 feat(pagination): add pagination component
  packages/components/src/components/pagination/Pagination.tsx
  packages/components/src/components/pagination/__test__/Pagination.test.js
  packages/components/src/components/pagination/__test__/__snapshots__/Pagination.test.js.snap
  packages/components/src/components/pagination/index.tsx
  packages/components/src/components/pagination/interface.tsx
  packages/components/src/components/pagination/style/index.less
  packages/components/src/index.ts
  packages/icons/src/LeftDoubleOutlined.tsx
  packages/icons/src/LeftOutlined.tsx
  packages/icons/src/RightDoubleOutlined.tsx
  packages/icons/src/RightOutlined.tsx
  packages/icons/src/Warning.tsx
  packages/icons/src/index.tsx
  packages/icons/svgs/left-double-outlined.svg
  packages/icons/svgs/left-outlined.svg
  packages/icons/svgs/right-double-outlined.svg
  packages/icons/svgs/right-outlined.svg
  packages/tokens/properties/color/background.json
  packages/tokens/properties/color/border.json
  packages/tokens/properties/color/text.json
  packages/tokens/properties/shadow.json
  packages/website/src/components/functional/pagination/demo/base.tsx
  packages/website/src/components/functional/pagination/demo/controlled.tsx
  packages/website/src/components/functional/pagination/demo/disable.tsx
  packages/website/src/components/functional/pagination/demo/nine.tsx
  packages/website/src/components/functional/pagination/demo/quickJumper.tsx
  packages/website/src/components/functional/pagination/index.zh-CN.md
Labels: add to next version, icon, token

#60 feat: add menu component
  packages/components/package.json
  packages/components/src/components/menu/Menu.tsx
  packages/components/src/components/menu/MenuContext.ts
  packages/components/src/components/menu/MenuItem.tsx
  packages/components/src/components/menu/MenuTitle.tsx
  packages/components/src/components/menu/SubMenu.tsx
  packages/components/src/components/menu/index.tsx
  packages/components/src/components/menu/interface.ts
  packages/components/src/components/menu/style/index.less
  packages/components/src/components/menu/style/index.ts
  packages/components/src/components/menu/style/mixin.less
  packages/tokens/properties/color/background.json
  packages/website/src/components/basic/menu/demos/demo.less
  packages/website/src/components/basic/menu/demos/horizontal.tsx
  packages/website/src/components/basic/menu/demos/vertical.tsx
  packages/website/src/components/basic/menu/index.zh-CN.md
  yarn.lock
Labels: add to next version, enhancement, token

#64 feat: add drawer component
  .eslintrc.js
  packages/components/package.json
  packages/components/src/components/config-provider/context.tsx
  packages/components/src/components/config-provider/index.tsx
  packages/components/src/components/drawer/index.tsx
  packages/components/src/components/drawer/style/customize.less
  packages/components/src/components/drawer/style/drawer.less
  packages/components/src/components/drawer/style/index.less
  packages/components/src/components/drawer/style/rtl.less
  packages/components/src/components/input/InputHidden.tsx
  packages/components/src/components/input/InputNumber.tsx
  packages/components/src/components/input/style/index.less
  packages/components/src/index.ts
  packages/components/src/utils/type.ts
  packages/tokens/properties/palette.json
  packages/website/src/components/basic/drawer/demo/customPosition.tsx
  packages/website/src/components/basic/drawer/demo/index.tsx
  packages/website/src/components/basic/drawer/index.zh-CN.md
  packages/website/src/components/basic/input/demo/Input.tsx
  packages/website/src/components/basic/input/demo/InputHidden.tsx
  packages/website/src/components/basic/input/demo/InputNumber.tsx
  packages/website/src/components/basic/input/demo/Password.tsx
  packages/website/src/components/basic/input/demo/TextArea.tsx
  packages/website/src/components/basic/toast/demo/index.tsx
  yarn.lock
Labels: add to next version, enhancement, token

#92 feat(button): add icon button and update tokens
  packages/components/src/components/button/style/index.less
  packages/components/src/components/button/style/mixin.less
  packages/tokens/properties/color/background.json
  packages/tokens/properties/color/border.json
  packages/tokens/properties/color/text.json
  packages/tokens/properties/palette.json
  packages/website/src/components/basic/button/demos/icon.tsx
  packages/website/src/components/basic/button/demos/index.less
  packages/website/src/components/basic/button/demos/primary.tsx
  packages/website/src/components/basic/button/demos/secondary.tsx
  packages/website/src/components/basic/button/index.zh-CN.md
Labels: add to next version, enhancement, token

#76 修改toggles token值
  packages/components/src/components/alert/style/index.less
  packages/components/src/components/toggles/style/index.less
  packages/tokens/properties/color/background.json
  packages/tokens/properties/color/border.json
  packages/tokens/properties/color/text.json
  packages/tokens/properties/shadow.json
Labels: token

#93 refactor(tag): refactor tag with new tokens
  packages/components/src/components/tag/Tag.tsx
  packages/components/src/components/tag/__tests__/Tag.test.js
  packages/components/src/components/tag/__tests__/__snapshots__/Tag.test.js.snap
  packages/components/src/components/tag/interface.ts
  packages/components/src/components/tag/style/index.less
  packages/tokens/properties/color/background.json
  packages/tokens/properties/color/text.json
  packages/website/src/components/basic/tag/demos/basic.tsx
  packages/website/src/components/basic/tag/demos/closable.tsx
  packages/website/src/components/basic/tag/demos/hoverClose.tsx
  packages/website/src/components/basic/tag/demos/version.tsx
  packages/website/src/components/basic/tag/index.zh-CN.md
Labels: refactor, token

#96 style(tokens): remove unused token for tree
  packages/components/src/components/tree/style/index.less
  packages/tokens/properties/color/text.json
Labels: token

#98 fix(input): update tokens of input
  packages/components/src/components/input/InputNumber.tsx
  packages/components/src/components/input/style/index.less
  packages/tokens/properties/color/border.json
  packages/tokens/properties/palette.json
  packages/website/src/components/basic/input/index.zh-CN.md
Labels: add to next version, token

#101 Fix: change input placeholder token
  packages/components/src/components/input/style/index.less
Labels: bug

#102 chore(website): gio-design@20.8.3 changelog
  lerna.json
  package.json
  packages/components/package.json
  packages/icons/package.json
  packages/tokens/package.json
  packages/website/package.json
  packages/website/src/develop/changelog/components.zh-CN.md
  packages/website/src/develop/changelog/icons.zh-CN.md
  packages/website/src/develop/changelog/tokens.zh-CN.md
  yarn.lock
Labels: documentation

#106 feat: add upload component
  packages/components/package.json
  packages/components/src/components/input/index.tsx
  packages/components/src/components/loading/interface.ts
  packages/components/src/components/upload/Actions.tsx
  packages/components/src/components/upload/Preview.tsx
  packages/components/src/components/upload/Upload.tsx
  packages/components/src/components/upload/UploadContext.tsx
  packages/components/src/components/upload/__tests__/__snapshots__/upload.test.js.snap
  packages/components/src/components/upload/__tests__/upload.test.js
  packages/components/src/components/upload/index.tsx
  packages/components/src/components/upload/interface.ts
  packages/components/src/components/upload/style/index.less
  packages/components/src/components/upload/style/index.ts
  packages/components/src/components/upload/tests/mock.js
  packages/components/src/components/upload/tests/mount.js
  packages/components/src/components/upload/triggers/AvatarTrigger.tsx
  packages/components/src/components/upload/triggers/ButtonTrigger.tsx
  packages/components/src/components/upload/triggers/CardTrigger.tsx
  packages/components/src/components/upload/triggers/DragTrigger.tsx
  packages/components/src/components/upload/triggers/InputTrigger.tsx
  packages/components/src/components/upload/utils.ts
  packages/components/src/components/upload/xhrRequest.ts
  packages/components/src/index.ts
  packages/components/src/typings/index.d.ts
  packages/icons/src/Delete.tsx
  packages/icons/src/File.tsx
  packages/icons/src/FileCsv.tsx
  packages/icons/src/FileDoc.tsx
  packages/icons/src/FilePdf.tsx
  packages/icons/src/FileXlsx.tsx
  packages/icons/src/Pic.tsx
  packages/icons/src/Picture.tsx
  packages/icons/src/Upload.tsx
  packages/icons/src/index.tsx
  packages/icons/svgs/delete.svg
  packages/icons/svgs/file-csv.svg
  packages/icons/svgs/file-doc.svg
  packages/icons/svgs/file-pdf.svg
  packages/icons/svgs/file-xlsx.svg
  packages/icons/svgs/file.svg
  packages/icons/svgs/picture.svg
  packages/icons/svgs/upload.svg
  packages/website/src/components/functional/upload/demos/avatar.tsx
  packages/website/src/components/functional/upload/demos/button.tsx
  packages/website/src/components/functional/upload/demos/card.tsx
  packages/website/src/components/functional/upload/demos/commonSets.ts
  packages/website/src/components/functional/upload/demos/drag.tsx
  packages/website/src/components/functional/upload/demos/input.tsx
  packages/website/src/components/functional/upload/index.zh-CN.md
  yarn.lock
Labels: add to next version, icon

#127 feat(components，website): 给button添加tooltip
  packages/components/src/components/button/button.tsx
  packages/components/src/components/button/interface.tsx
  packages/website/src/components/basic/button/index.zh-CN.md
Labels: add to next version

#129 feat(pagination): add hideOnSinglePage prop
  packages/components/src/components/pagination/Pagination.tsx
  packages/components/src/components/pagination/__test__/Pagination.test.js
  packages/components/src/components/pagination/interface.tsx
  packages/website/src/components/functional/pagination/index.zh-CN.md
Labels: add to next version

#143 feat(loading): add blurColor prop
  packages/components/src/components/loading/Loading.tsx
  packages/components/src/components/loading/__test__/Loading.test.js
  packages/components/src/components/loading/__test__/__snapshots__/Loading.test.js.snap
  packages/components/src/components/loading/interface.ts
  packages/components/src/components/loading/style/index.less
  packages/tokens/properties/color/background.json
  packages/website/src/components/basic/loading/demos/blurColor.tsx
  packages/website/src/components/basic/loading/index.zh-CN.md
Labels: add to next version, token

#136 feat(banner): add banner
  packages/components/src/components/banner/Banner.tsx
  packages/components/src/components/banner/__tests__/Banner.spec.js
  packages/components/src/components/banner/__tests__/__snapshots__/Banner.spec.js.snap
  packages/components/src/components/banner/index.tsx
  packages/components/src/components/banner/interface.ts
  packages/components/src/components/banner/style/index.less
  packages/components/src/utils/hooks/useHover.ts
  packages/components/src/utils/hooks/useToggle.ts
  packages/tokens/properties/color/background.json
  packages/tokens/properties/color/text.json
  packages/website/src/components/functional/banner/demo/alert.tsx
  packages/website/src/components/functional/banner/demo/base.tsx
  packages/website/src/components/functional/banner/demo/closeable.tsx
  packages/website/src/components/functional/banner/demo/index.less
  packages/website/src/components/functional/banner/index.zh-CN.md
Labels: add to next version, token

#159 docs: update icon component's documentation
  packages/website/src/resources/iconDemos/assets/filled.svg
  packages/website/src/resources/iconDemos/assets/outlined.svg
  packages/website/src/resources/iconDemos/index.less
  packages/website/src/resources/iconDemos/index.tsx
  packages/website/src/resources/iconDemos/svgs.tsx
  packages/website/src/resources/icons.en-US.md
  packages/website/src/resources/icons.zh-CN.md
Labels: documentation

#162 docs(website): update design tokens' demo
  packages/website/src/resources/tokenDemos/backgroundTable.tsx
  packages/website/src/resources/tokenDemos/borderColorTable.tsx
  packages/website/src/resources/tokenDemos/borderRadiusTable.tsx
  packages/website/src/resources/tokenDemos/examples.less
  packages/website/src/resources/tokenDemos/examples.tsx
  packages/website/src/resources/tokenDemos/fontFamilyTable.tsx
  packages/website/src/resources/tokenDemos/fontSizeTable.tsx
  packages/website/src/resources/tokenDemos/fontWeightTable.tsx
  packages/website/src/resources/tokenDemos/interface.ts
  packages/website/src/resources/tokenDemos/kvTable.tsx
  packages/website/src/resources/tokenDemos/paletteTable.tsx
  packages/website/src/resources/tokenDemos/shadowTable.tsx
  packages/website/src/resources/tokenDemos/spacingSizeTable.tsx
  packages/website/src/resources/tokenDemos/textColorTable.tsx
  packages/website/src/resources/tokenDemos/tokenTable.less
  packages/website/src/resources/tokenDemos/tokenTable.tsx
  packages/website/src/resources/tokenDemos/tokens.tsx
  packages/website/src/resources/tokenDemos/utils.ts
  packages/website/src/resources/tokens.en-US.md
  packages/website/src/resources/tokens.zh-CN.md
Labels: documentation
