Repository growingio/gio-design, pull requests merged in 2020-12, with the labels that each got.

#562 feat(select): 增加JSX方式添加Option
  packages/components/src/assets/images/BoxFilled.svg
  packages/components/src/components/list/list.tsx
  packages/components/src/components/list/style/option.less
  packages/components/src/components/select/OptGroup.tsx
  packages/components/src/components/select/Options.tsx
  packages/components/src/components/select/Select.tsx
  packages/components/src/components/select/__tests__/Select.test.js
  packages/components/src/components/select/__tests__/__snapshots__/Select.test.js.snap
  packages/components/src/components/select/index.tsx
  packages/components/src/components/select/interface.ts
  packages/components/src/components/select/style/index.less
  packages/components/src/index.ts
  packages/website/src/components/functional/select/demos/customizeoptions.tsx
  packages/website/src/components/functional/select/demos/options.ts
  packages/website/src/components/functional/select/index.zh-CN.md
Labels: add to next version

#569 fix(table): add border-radius to table when placeholder
  packages/components/src/components/alert/style/index.less
  packages/components/src/components/input/style/index.less
  packages/components/src/components/menu/MenuItem.tsx
  packages/components/src/components/menu/style/index.less
  packages/components/src/components/table/style/index.less
  packages/website/src/components/basic/alert/demo/alertClose.tsx
  packages/website/src/components/basic/alert/demo/alertDecription.tsx
  packages/website/src/components/basic/alert/demo/alertIcon.tsx
  packages/website/src/components/basic/alert/demo/alertOnlyDecription.tsx
  packages/website/src/components/basic/alert/demo/alertStyle.tsx
  packages/website/src/components/basic/alert/demo/demo.less
  packages/website/src/components/basic/menu/demos/vertical.tsx
Labels: add to next version

#576 feat(pagination): add select pagesize feature
  packages/components/src/components/input/style/index.less
  packages/components/src/components/pagination/Pagination.tsx
  packages/components/src/components/pagination/__test__/Pagination.test.js
  packages/components/src/components/pagination/__test__/__snapshots__/Pagination.test.js.snap
  packages/components/src/components/pagination/interface.tsx
  packages/components/src/components/pagination/style/index.less
  packages/components/src/components/pagination/style/index.ts
  packages/components/src/components/table/hook/usePagination.tsx
  packages/website/src/components/functional/pagination/demo/disable.tsx
  packages/website/src/components/functional/pagination/demo/sizeChanger.tsx
  packages/website/src/components/functional/pagination/index.zh-CN.md
  packages/website/src/components/functional/table/demo/pagination.tsx
Labels: add to next version

#592 style(table): update table filter style
  packages/components/src/components/list/style/base.less
  packages/components/src/components/table/FilterPopover.tsx
  packages/components/src/components/table/__test__/Table.test.js
  packages/components/src/components/table/style/index.less
Labels: add to next version

#596 fix(list): fix list item spacing
  packages/components/src/assets/images/BoxFilled.svg
  packages/components/src/components/list/list.tsx
  packages/components/src/components/list/style/base.less
  packages/components/src/components/list/style/option.less
  packages/components/src/components/select/Empty.tsx
  packages/components/src/components/select/Select.tsx
  packages/components/src/components/select/style/empty.less
  packages/website/src/components/functional/list/demo/avatar.tsx
  packages/website/src/components/functional/list/demo/group.tsx
Labels: add to next version

#601 refactor(tabs, tab-nav): refactor tabs and tab-nav
  packages/components/src/components/tab-nav/TabNav.tsx
  packages/components/src/components/tab-nav/__test__/TabNav.test.js
  packages/components/src/components/tab-nav/interface.ts
  packages/components/src/components/tabs/Tabs.tsx
  packages/components/src/components/tabs/__tests__/Tabs.test.js
  packages/components/src/components/tabs/interface.ts
  packages/components/src/utils/hooks/useDeepCompareMemo.ts
  packages/website/src/components/basic/tabnav/index.zh-CN.md
  packages/website/src/components/basic/tabs/demo/block.tsx
  packages/website/src/components/basic/tabs/index.zh-CN.md
Labels: add to next version

#606 style(input/date_picker): change input disabled color
  packages/components/src/components/date-picker/dateRangePicker.tsx
  packages/components/src/components/date-picker/style/index.less
  packages/components/src/components/input/style/index.less
  packages/components/src/index.ts
Labels: add to next version

#607 fix(upload): update file in non-default case
  packages/components/src/components/upload/Upload.tsx
  packages/components/src/components/upload/utils.ts
Labels: add to next version

#581 fix(toggles): add checked control what toggles's status change
  packages/components/src/components/toggles/__test__/toggles.test.js
  packages/components/src/components/toggles/interface.ts
  packages/components/src/components/toggles/style/index.less
  packages/components/src/components/toggles/toggles.tsx
  packages/website/src/components/basic/toggles/demo/toggles.tsx
  packages/website/src/components/basic/toggles/index.zh-CN.md
Labels: add to next version

#620 feat(sign): add offset prop
  packages/components/src/components/sign/Number.tsx
  packages/components/src/components/sign/Sign.tsx
  packages/components/src/components/sign/__tests__/__snapshots__/sign.test.js.snap
  packages/components/src/components/sign/interface.ts
  packages/components/src/components/sign/style/index.less
  packages/website/src/components/basic/sign/demos/sign.tsx
  packages/website/src/components/basic/sign/index.zh-CN.md
Labels: add to next version

#626 feat(icon): add picture outlined icon
  packages/components/src/components/upload/triggers/DragTrigger.tsx
  packages/icons/src/Empty.tsx
  packages/icons/src/PictureOutlined.tsx
  packages/icons/src/index.tsx
  packages/icons/svgs/picture-outlined.svg
Labels: 📎 icon

#625 fix(tab-nav, tabs): fix style bug caused by #601 PR
  packages/components/src/components/tab-nav/TabNav.tsx
  packages/components/src/components/tab-nav/style/index.less
  packages/website/src/components/basic/tabnav/demos/line.tsx
Labels: add to next version

#632 docs(release): version 20.12.3 change log
  packages/components/package.json
  packages/website/src/develop/changelog/components.zh-CN.md
Labels: 📃 documentation

#634 feat(select): new feature allowClear
  packages/components/src/components/list/interface.ts
  packages/components/src/components/list/list.tsx
  packages/components/src/components/select/Select.tsx
  packages/components/src/components/select/__tests__/__snapshots__/Select.test.js.snap
  packages/components/src/components/select/interface.ts
  packages/components/src/components/select/style/index.less
  packages/website/src/components/functional/select/demos/multiple.tsx
  packages/website/src/components/functional/select/demos/single.tsx
  packages/website/src/components/functional/select/index.zh-CN.md
Labels: add to next version

#633 fix(alert): fix style error width exceeds the parent element
  packages/components/src/components/alert/style/index.less
Labels: add to next version

#652 fix: 修复嵌套 container 宽度计算错乱逻辑
  packages/components/src/components/grid/index.tsx
  packages/components/src/components/grid/style/index.less
  packages/website/src/components/basic/grid/demo/nested-container.tsx
  packages/website/src/components/basic/grid/index.zh-CN.md
Labels: add to next version

#657 fix(modal): fix the modal click onOk don't close in CalloutModal
  packages/components/src/components/modal/CalloutModal.tsx
Labels: add to next version
